### ISSUE TITLE
As a admin, I’d like to be able to access operators, so that I’ll have the potential to update/block operators

### ISSUE THREAD

**Issue by anjaliUvt** [first-thing-first/sample#22]
- [ ] Shows all registered operators and its details in a table #24 

- [ ] Add operators with name, username, email, location and contact number #23 

- [ ] Block/unblock privacy feature for each operator #25 

- [ ] Edit and update each operator’s details, except the username #26 

- [ ] Search operators by name #27 

- [ ] Logout #28

**Comment by anjaliUvt** [comment]
- [ ]Shows all registered operators and its details in a table #24
