### ISSUE TITLE
OPERATOR

### ISSUE THREAD

**Issue by anjaliUvt** [first-thing-first/sample#29]
- [ ] Login operator with username and system generated password #30 

- [ ] Add/register #31 

- [ ] Edit and update each sub operator’s details, except username #32 

- [ ] Block/unblock privacy feature for each sub operator #33 

- [ ] Delete for each sub operator #34 

- [ ] Search by sub operator’s name #35 

- [ ] operator can set their mob app name #36 

- [ ] operator can choose a logo for their mob app #36 

- [ ] Change password #37 

- [ ] Logout operator #38

**Comment by anjaliUvt** [comment]
- [ ] Login operator with username and system generated password #30
